apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql
  spec:
    selector:
      matchLabels:
        app: mysql8
    replecas: 2
    template:
      metadata:
        labels:
          app: mysql8
      spec:
        containers:
        - name: mysql8
          image: mysql:8.0 
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: krittawat
        - name: MYSQL_DATABASE
          value: myweb
        - name: MYSQL_USER
          value: root # MYsql USER
        - name: MYSQL_PASSWORD
          value: krittawat
        args: ["--default-authentication-plugin=mysql_native_password"]
        ports:
        - containerPort: 3306
        name: mysql8
