apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
 # replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql_db
        image: mysql:8.0 
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: krittawat
          - name: MYSQL_DATABASE
            value: myweb
          - name: MYSQL_USER
            value: root # MYsql USER
          - name: MYSQL_PASSWORD
            value: krittawat
            args: ["--default-authentication-plugin=mysql_native_password"]
        ports:
          - containerPort: 3306
            name: mysql8