apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: myweb
spec:
  ports:
    - port: 3306
  selector:
    app: myweb
    tier: mysql
  #clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqlvol
  labels:
    app: myweb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress-mysql
  labels:
    app: myweb
spec:
  selector:
    matchLabels:
      app: myweb
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: myweb
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: krittawat
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysqlvol
          mountPath: /var/lib/mysql
      volumes:
      - name: mysqlvol
        persistentVolumeClaim:
          claimName: mysqlvol
